### ISSUE TITLE
Example of using ornac's own binary cache?

### ISSUE THREAD

**Issue by Animeshz** [linyinfeng/oranc#20]
It seems to me that this repository pushes its own binary cache into ghcr.

It would be really helpful if public key can be released and its setup documented to - for example install ornac before anything else from the cache!

**Comment by linyinfeng** [comment]
Currently, its binary cache is pushed to <https://linyinfeng.cachix.org> by CI and is not pushed to ghcr.io.

In fact, I am not sure if oranc is violating GitHub's ToS... so I'm not actively using it. As you can see, the CI of oranc itself is using cachix. Maybe I should add a warning in `README.md`.

**Comment by Animeshz** [comment]
Oh, thanks for the information!

> In fact, I am not sure if oranc is violating GitHub's ToS... so I'm not actively using it. As you can see, the CI of oranc itself is using cachix. Maybe I should add a warning in `README.md`.

Is it so? Because I was just considering using it instead of [attic](https://github.com/zhaofengli/attic) + s3 bucket for just some personal use. Is this implementation just for prototype :thinking:?

**Comment by linyinfeng** [comment]
> Oh, thanks for the information!
> 
> > In fact, I am not sure if oranc is violating GitHub's ToS... so I'm not actively using it. As you can see, the CI of oranc itself is using cachix. Maybe I should add a warning in `README.md`.
> 
> Is it so? Because I was just considering using it instead of [attic](https://github.com/zhaofengli/attic) + s3 bucket for just some personal use. Is this implementation just for prototype thinking?

It can be considered a prototype because it currently lacks the extensibility to support CA realization. But without CA, it is tested and works, and I tried pushing gigabytes of binary caches to ghcr.io (deleted after the test). I also implemented a github action <https://github.com/linyinfeng/oranc-action> to use it just like cachix.

But the tags, image manifests, and layers it creates are so different from other typical oci repositories. So I don't know if it is an abuse of oci registries.

I made this, because if it is allowed by GitHub, then we have free binary caches of infinite size, without the need of garbage collecting.
